---

- hosts: all
  remote_user: root
  gather_facts: false
  pre_tasks:
  - name: create .ssh folder
    local_action: shell test ! -d ~/.ssh && mkdir -p ~/.ssh
  - name: run ssh-keyscan to add keys to known_hosts
    local_action: shell ssh-keyscan {{ ansible_ssh_host }} >> ~/.ssh/known_hosts
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:

  tasks:
  - name: Install packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - git

  roles:
  - docker

...
