---

- name: ensure volumes exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ semaphore.playbook_path }}"

- name: template config files
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
  with_items:
    - "{ src: 'env', dest: {{ semaphore.playbook_path }}"


