---

- name: ensure volumes exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ local_semaphore_root_path }}"
  - "{{ local_semaphore.playbook_path }}"
  - "{{ local_semaphore.data_path }}"

- name: template config files
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
  with_items:
    - { src: 'env', dest: "{{ local_semaphore_root_path }}" }

- name: start mysql containers
  docker_container:
    name: semaphore-mysql
    image: mysql:5
    volumes:
    - "{{ local_semaphore.data_path }}:/var/lib/mysql"
    env_file: "{{ local_semaphore_root_path }}/env"

- name: start semaphore container
  docker_container:
    name: semaphore
    image: doubtingben/local-semaphore
    volumes:
    - "{{ local_semaphore.playbook_path }}:/semaphore"
    links:
    - semaphore-mysql:semaphore-mysql
    env_file: "{{ local_semaphore_root_path }}/env"

- name: start nginx container
  docker_container:
    name: semaphore-nginx
    image: nginx:1
    volumes:
    - "{{ local_semaphore.certs }}:/etc/nginx/ssl"
    exposed_ports:
    - 80
    - 443

...
